#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
xfce4-clipman &
deadd-notification-center &
bspc monitor -d I II III IV V 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding          15

bspc config normal_border_color "#2e3440"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#8fbcbb"
bspc config presel_feedback_color "#6272a4"

bspc rule -a Pavucontrol state=floating

if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

polybar -r bar
feh --bg-fill ~/Images/Wallpapers/2e3440.png
